### ISSUE TITLE
CurseForge release

### ISSUE THREAD

**Issue by Madis0** [booky10/StackDeobfuscator#3]
**Is your feature request related to a problem? Please describe.**
Can't find the mod on CurseForge.

**Describe the solution you'd like**
Add it to CurseForge.

**Describe alternatives you've considered**
N/A

**Additional info**
Modpacks and exposure :)

**Comment by booky10** [comment]
https://www.curseforge.com/minecraft/mc-mods/stackdeobf
still waiting for approval, will close this once approved

**Comment by booky10** [comment]
seems to be approved
