### ISSUE TITLE
Exception while mapping More Culling crash report

### ISSUE THREAD

**Issue by Steveplays28** [booky10/StackDeobfuscator#7]
**Describe the bug**
[Log file (mclo.gs)](https://mclo.gs/z5bL4Ue)

Something goes wrong while mapping this crash report: `java.lang.IllegalArgumentException: Illegal group reference`.
Seems like a regex matcher issue, looking at the log.

This exception makes the actual crash report unreadable.

**To Reproduce**
Follow the steps outlined in this [issue](https://github.com/fxmorin/MoreCulling/issues/182) on More Culling's repository.

**Expected behavior**
Correct mapping of the crash report's stacktraces.

**Screenshots**
N/A

**Minecraft Version:** `1.19.2`
**Fabric Loader Version:** Quilt loader `0.19.2-beta.2`
**Mod version:** `1.3.2`

**Additional info**
N/A

**Comment by Steveplays28** [comment]
Just saw #5, is this due to an incompatibility with Quilt?
Stack Deobfuscator seemed to work fine on a handful of other crash reports I had while working on my modpack.

**Comment by booky10** [comment]
I don't really know the cause of this (as java regex matchers don't tell you whats wrong... thanks)
i've implemented some additional checks in 4bfcb27032a17d5622955b0ac8ed0df32aef09b4 (can be downloaded from github actions, [direct download](https://github.com/booky10/StackDeobfuscator/suites/14091292142/artifacts/788008709)), which should hopefully fix this issue
please let me know if this actually fixes it

**Comment by Steveplays28** [comment]
Hey, sorry for the late response. Just tested the fix, works properly for me with the same MoreCulling crash.
Thanks for the quick fix!
