### ISSUE TITLE
Add text box in config menu to manually paste in a stack trace to remap

### ISSUE THREAD

**Issue by LoganDark** [booky10/StackDeobfuscator#8]
Because this mod doesn't seem to actually intercept any logs and [the other remapper got taken down](https://github.com/Draylar/minecraft-mapper/issues/10), I'd love if I can just paste in something from the log into a text box and have it remapped. In Mod Menu you can have a config button that opens a GUI, you could put something there that I can paste the stack trace into and click a button to have it remapped.

**Comment by LoganDark** [comment]
Even changing `rewrite-every-log-message` to `true` doesn't fix this. So yeah. In cases where the log messages don't actually get rewritten it would sure be nice to still be able to remap the stack traces

**Comment by booky10** [comment]
This is already possible, as this project has a web-module (see [wiki](https://github.com/booky10/StackDeobfuscator/wiki/Web-Remapping) for self-hosting). There is currently a public instance of this hosted at [stackdeobf.booky.dev](https://stackdeobf.booky.dev/) (although yarn doesn't work atm for some strange reason).
&nbsp;

> Even changing rewrite-every-log-message to true doesn't fix this. So yeah. In cases where the log messages don't actually get rewritten it would sure be nice to still be able to remap the stack traces manually

Do you use quilt or fabric? Quilt has some issues with mods injecting into the logger.

**Comment by LoganDark** [comment]
> There is currently a public instance of this hosted at [stackdeobf.booky.dev](https://stackdeobf.booky.dev/)

PLEASE put this in the readme somewhere so that I could have found this earlier!

> Do you use quilt or fabric? Quilt has some issues with mods injecting into the logger.

I use normal 100% legitimate fabric

**Comment by LoganDark** [comment]
Yeah I don't know what is going on I'm making sure my firewall properly allowed to connection to maven.fabricmc.net so maybe the asynchronous downloading is just screwed up or something. I'll try out the website.

**Comment by booky10** [comment]
Yeah, the checksum given by fabric's maven repository is not valid. Quilt and Mojang mappings work though.

**Comment by LoganDark** [comment]
> the checksum given by fabric's maven repository is not valid

Then stop verifying it.

Or give me an option to turn it off maybe?

**Comment by booky10** [comment]
Sha256 works, I've just switched to that.

Please also test [the latest workflow build](https://github.com/booky10/StackDeobfuscator/actions/runs/6814771573) to check if your problem with `rewrite-every-log-message` not working is fixed.

**Comment by LoganDark** [comment]
> your problem with `rewrite-every-log-message` not working

I'm 99% sure that's actually now because the mappings couldn't be loaded. I'll test that build though.

**Comment by LoganDark** [comment]
![image](https://github.com/booky10/StackDeobfuscator/assets/4723091/9af3a491-c8ee-4ca9-a181-efe5f35615ea)

Fixed

And I'll close this issue since the website exists

**Comment by LoganDark** [comment]
Thank you!
